### ISSUE TITLE
RuntimeError: expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by yzho0907** [Wangpeiyi9979/InformationExtractionDemo#2]
Traceback (most recent call last):
  File "/home/clife/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/clife/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/home/clife/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/clife/anaconda2/envs/py36/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/clife/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/clife/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/clife/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/clife/anaconda2/envs/py36/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/clife/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/clife/anaconda2/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/clife/Leo/InformationExtractionDemo/app.py", line 14, in IEDemo
    ieData = getTriple(text)
  File "/home/clife/Leo/InformationExtractionDemo/utils/findTriple.py", line 29, in getTriple
    _, triples = model(sen, None, None)
  File "/home/clife/anaconda2/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/clife/Leo/InformationExtractionDemo/utils/BERT_MUL_CNN.py", line 146, in forward
    all_tuples = torch.cat(all_tuples, 0)  # (B * tule_num, 1, tuple_max_len, bert_hidden_size)
RuntimeError: expected a non-empty list of Tensors
在预测的时候有时会报这个错误，请问下是什么原因引起的？这个地方是不是应该加个异常处理？

**Comment by Wangpeiyi9979** [comment]
嗯嗯，对的，这个模型先做命名实体识别，然后对实体进行两两配对，当句子里面没有配对实体的时候，会报错。
![image](https://user-images.githubusercontent.com/42565075/58181767-f8302700-7cde-11e9-83ae-aa4d456bd7b0.png)
![image](https://user-images.githubusercontent.com/42565075/58181811-0b42f700-7cdf-11e9-8039-d6ce98fe3416.png)

因为当时比赛官方说了每句话中必定存在三元组，加上测试集每句话也都提取除了能够配对的实体，我就没做这个判断了。

**Comment by yzho0907** [comment]
@Wangpeiyi9979 我看到一些参赛选手采用的joint model，应该能减少这种现象的出现，同时应该能一定程度的改善实体不全的问题。

**Comment by liutianling** [comment]
@yzho0907 pytorch_pretrained_bert这个模块在哪，报错找不到这个

**Comment by yzho0907** [comment]
@liutianling pip install pytorch_pretrained_bert
这个要安装的，你直接git上拷贝源码也可以
